apiVersion: v1
entries:
  cwf-orc8r:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2024-01-10T20:04:33.703370311+05:30"
    dependencies:
    - name: orc8rlib
      repository: file://../../../../orc8r/cloud/helm/orc8rlib
      version: 0.1.4
    description: A Helm chart for magma orchestrator's cwf module
    digest: 55492af447523dc0a7520f8d04766dca0f0ee9d90e9ea45a1e0e4438f467e1ab
    keywords:
    - magma
    - or8cr
    - cwf-orc8r
    name: cwf-orc8r
    sources:
    - https://github.com/magma/magma
    urls:
    - cwf-orc8r-1.8.0.tgz
    version: 1.8.0
  domain-proxy:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2024-01-10T20:04:33.704992389+05:30"
    description: A Helm chart for magma orchestrator's domain-proxy module.
    digest: 00096708ee37e3266d1eaf9b060cf347bdade9ac2b706925840436275db87aeb
    keywords:
    - magma
    - orc8r
    - dp
    name: domain-proxy
    sources:
    - https://github.com/magma/magma
    type: application
    urls:
    - domain-proxy-1.8.0.tgz
    version: 1.8.0
  efs-provisioner:
  - apiVersion: v1
    appVersion: v2.4.0
    created: "2024-01-10T20:04:33.705531575+05:30"
    deprecated: true
    description: DEPRECATED A Helm chart for the AWS EFS external storage provisioner
    digest: 46252c06f23091332120c793bdd63bb9f678fbf4c122a7519961b24d67b1bf00
    home: https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs
    name: efs-provisioner
    sources:
    - https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs
    - https://github.com/mirror/busybox
    urls:
    - efs-provisioner-0.13.2.tgz
    version: 0.13.2
  elasticsearch-curator:
  - apiVersion: v1
    appVersion: 5.7.6
    created: "2024-01-10T20:04:33.706148875+05:30"
    deprecated: true
    description: DEPRECATED A Helm chart for Elasticsearch Curator
    digest: c2f15e376f72f6163273e97fe8fe6f0c654e6943745389e7852ef4113a81fe21
    home: https://github.com/elastic/curator
    keywords:
    - curator
    - elasticsearch
    - elasticsearch-curator
    name: elasticsearch-curator
    sources:
    - https://github.com/kubernetes/charts/elasticsearch-curator
    - https://github.com/pires/docker-elasticsearch-curator
    urls:
    - elasticsearch-curator-2.2.3.tgz
    version: 2.2.3
  feg-orc8r:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2024-01-10T20:04:33.707045495+05:30"
    dependencies:
    - name: orc8rlib
      repository: file://../../../../orc8r/cloud/helm/orc8rlib
      version: 0.1.4
    description: A Helm chart for magma orchestrator's feg module
    digest: a700594c51121ef4df92491b22c645dcbb000a5878d37c55cfcb5c3a36b8f3b4
    keywords:
    - magma
    - or8cr
    - feg-orc8r
    name: feg-orc8r
    sources:
    - https://github.com/magma/magma
    urls:
    - feg-orc8r-1.8.0.tgz
    version: 1.8.0
  fluentd:
  - apiVersion: v1
    appVersion: v2.4.0
    created: "2024-01-10T20:04:33.707918442+05:30"
    description: A Fluentd Elasticsearch Helm chart for Kubernetes.
    digest: f77ce45253caa7e9b940269ced9594765c81094f9b45502c101a5898edd2a40b
    home: https://www.fluentd.org/
    icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
    maintainers:
    - email: pete.brown@powerhrg.com
      name: rendhalver
    - email: maxime@root314.com
      name: miouge1
    - email: hfernandez@mesosphere.com
      name: hectorj2f
    name: fluentd
    sources:
    - https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image
    - https://quay.io/repository/coreos/fluentd-kubernetes
    - https://github.com/coreos/fluentd-kubernetes-daemonset
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html
    urls:
    - fluentd-2.3.2.tgz
    version: 2.3.2
  lte-orc8r:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2024-01-10T20:04:33.70971072+05:30"
    dependencies:
    - name: orc8rlib
      repository: file://../../../../orc8r/cloud/helm/orc8rlib
      version: 0.1.4
    description: A Helm chart for magma orchestrator's lte module
    digest: d98e56e10cc1c1e9f3b51a132f11d4ba8d4bcfb26eb5d5a2b4b734ea13cfc8fa
    keywords:
    - magma
    - or8cr
    - lte-orc8r
    name: lte-orc8r
    sources:
    - https://github.com/magma/magma
    urls:
    - lte-orc8r-1.8.0.tgz
    version: 1.8.0
  orc8r:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2024-01-10T20:04:33.717182522+05:30"
    dependencies:
    - condition: certs.create
      name: certs
      repository: ""
      version: 0.1.0
    - condition: secrets.create
      name: secrets
      repository: ""
      version: 0.1.10
    - condition: metrics.enabled
      name: metrics
      repository: ""
      version: 1.4.24
    - condition: nms.enabled
      name: nms
      repository: ""
      version: 0.1.12
    - condition: logging.enabled
      name: logging
      repository: ""
      version: 0.1.10
    - name: orc8rlib
      repository: file://../orc8rlib
      version: 0.1.4
    description: Helm chart for the Magma Orchestrator
    digest: 2e377902d2ac6a8454749856832ba055e6dac370b4bf90161e2c0bc225fa44af
    home: https://www.magmacore.org
    keywords:
    - magma
    - orc8r
    name: orc8r
    sources:
    - https://github.com/magma/magma
    urls:
    - orc8r-1.8.0.tgz
    version: 1.8.0
generated: "2024-01-10T20:04:33.702483883+05:30"
