apiVersion: v1
entries:
  cwf-orc8r:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2023-09-26T16:30:11.321265394+05:30"
    dependencies:
    - name: orc8rlib
      repository: file://../../../../orc8r/cloud/helm/orc8rlib
      version: 0.1.4
    description: A Helm chart for magma orchestrator's cwf module
    digest: 3807a6736168bbe03d4efbfcad50fa04f20ade0594e709c0f663a96869e71f32
    keywords:
    - magma
    - or8cr
    - cwf-orc8r
    name: cwf-orc8r
    sources:
    - https://github.com/magma/magma
    urls:
    - cwf-orc8r-1.8.0.tgz
    version: 1.8.0
  domain-proxy:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2023-09-26T16:30:11.322931385+05:30"
    description: A Helm chart for magma orchestrator's domain-proxy module.
    digest: 04dbe07f492b9c8b172ad404bf30a1a7e9f0b9b990d094cba67d915c81ae9932
    keywords:
    - magma
    - orc8r
    - dp
    name: domain-proxy
    sources:
    - https://github.com/magma/magma
    type: application
    urls:
    - domain-proxy-1.8.0.tgz
    version: 1.8.0
  efs-provisioner:
  - apiVersion: v1
    appVersion: v2.4.0
    created: "2023-09-26T16:30:11.3236282+05:30"
    deprecated: true
    description: DEPRECATED A Helm chart for the AWS EFS external storage provisioner
    digest: 46252c06f23091332120c793bdd63bb9f678fbf4c122a7519961b24d67b1bf00
    home: https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs
    name: efs-provisioner
    sources:
    - https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs
    - https://github.com/mirror/busybox
    urls:
    - efs-provisioner-0.13.2.tgz
    version: 0.13.2
  elasticsearch-curator:
  - apiVersion: v1
    appVersion: 5.7.6
    created: "2023-09-26T16:30:11.324348743+05:30"
    deprecated: true
    description: DEPRECATED A Helm chart for Elasticsearch Curator
    digest: c2f15e376f72f6163273e97fe8fe6f0c654e6943745389e7852ef4113a81fe21
    home: https://github.com/elastic/curator
    keywords:
    - curator
    - elasticsearch
    - elasticsearch-curator
    name: elasticsearch-curator
    sources:
    - https://github.com/kubernetes/charts/elasticsearch-curator
    - https://github.com/pires/docker-elasticsearch-curator
    urls:
    - elasticsearch-curator-2.2.3.tgz
    version: 2.2.3
  feg-orc8r:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2023-09-26T16:30:11.325370836+05:30"
    dependencies:
    - name: orc8rlib
      repository: file://../../../../orc8r/cloud/helm/orc8rlib
      version: 0.1.4
    description: A Helm chart for magma orchestrator's feg module
    digest: 68f4f3d7883fce83750fccc8fbc6c7ac8bd61de73eda2ac332ef44079695d1b2
    keywords:
    - magma
    - or8cr
    - feg-orc8r
    name: feg-orc8r
    sources:
    - https://github.com/magma/magma
    urls:
    - feg-orc8r-1.8.0.tgz
    version: 1.8.0
  fluentd:
  - apiVersion: v1
    appVersion: v2.4.0
    created: "2023-09-26T16:30:11.326330646+05:30"
    description: A Fluentd Elasticsearch Helm chart for Kubernetes.
    digest: f77ce45253caa7e9b940269ced9594765c81094f9b45502c101a5898edd2a40b
    home: https://www.fluentd.org/
    icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
    maintainers:
    - email: pete.brown@powerhrg.com
      name: rendhalver
    - email: maxime@root314.com
      name: miouge1
    - email: hfernandez@mesosphere.com
      name: hectorj2f
    name: fluentd
    sources:
    - https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image
    - https://quay.io/repository/coreos/fluentd-kubernetes
    - https://github.com/coreos/fluentd-kubernetes-daemonset
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html
    urls:
    - fluentd-2.3.2.tgz
    version: 2.3.2
  lte-orc8r:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2023-09-26T16:30:11.3274291+05:30"
    dependencies:
    - name: orc8rlib
      repository: file://../../../../orc8r/cloud/helm/orc8rlib
      version: 0.1.4
    description: A Helm chart for magma orchestrator's lte module
    digest: fbd79bed8d23d5755418b32596ca103a69cf468cc8e7f6fde4386eca7a4831cd
    keywords:
    - magma
    - or8cr
    - lte-orc8r
    name: lte-orc8r
    sources:
    - https://github.com/magma/magma
    urls:
    - lte-orc8r-1.8.0.tgz
    version: 1.8.0
  orc8r:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2023-09-26T16:30:11.336162327+05:30"
    dependencies:
    - condition: certs.create
      name: certs
      repository: ""
      version: 0.1.0
    - condition: secrets.create
      name: secrets
      repository: ""
      version: 0.1.10
    - condition: metrics.enabled
      name: metrics
      repository: ""
      version: 1.4.24
    - condition: nms.enabled
      name: nms
      repository: ""
      version: 0.1.12
    - condition: logging.enabled
      name: logging
      repository: ""
      version: 0.1.10
    - name: orc8rlib
      repository: file://../orc8rlib
      version: 0.1.4
    description: Helm chart for the Magma Orchestrator
    digest: 9d57ba180b4ab1219665c2e9400715e9a8d51c92e27a10c6f21bfe393efb5f68
    home: https://www.magmacore.org
    keywords:
    - magma
    - orc8r
    name: orc8r
    sources:
    - https://github.com/magma/magma
    urls:
    - orc8r-1.8.0.tgz
    version: 1.8.0
generated: "2023-09-26T16:30:11.320109779+05:30"
