apiVersion: v1
entries:
  openebs:
  - apiVersion: v2
    appVersion: 3.8.0
    created: "2023-09-15T16:50:20.964539554+05:30"
    dependencies:
    - condition: openebs-ndm.enabled
      name: openebs-ndm
      repository: https://openebs.github.io/node-disk-manager
      version: 2.1.0
    - condition: localpv-provisioner.enabled
      name: localpv-provisioner
      repository: https://openebs.github.io/dynamic-localpv-provisioner
      version: 3.4.0
    - condition: cstor.enabled
      name: cstor
      repository: https://openebs.github.io/cstor-operators
      version: 3.5.0
    - condition: jiva.enabled
      name: jiva
      repository: https://openebs.github.io/jiva-operator
      version: 3.5.0
    - condition: zfs-localpv.enabled
      name: zfs-localpv
      repository: https://openebs.github.io/zfs-localpv
      version: 2.3.0
    - condition: lvm-localpv.enabled
      name: lvm-localpv
      repository: https://openebs.github.io/lvm-localpv
      version: 1.2.0
    - condition: nfs-provisioner.enabled
      name: nfs-provisioner
      repository: https://openebs.github.io/dynamic-nfs-provisioner
      version: 0.10.0
    - condition: mayastor.enabled
      name: mayastor
      repository: https://openebs.github.io/mayastor-extensions
      version: 2.3.0
    description: Containerized Attached Storage for Kubernetes
    digest: dfbe7599abca1b9af8ee4c2c1147060fce24583d8570642636a8f4adc880fe4c
    home: http://www.openebs.io/
    icon: https://raw.githubusercontent.com/cncf/artwork/HEAD/projects/openebs/icon/color/openebs-icon-color.png
    keywords:
    - cloud-native-storage
    - block-storage
    - local-storage
    - iSCSI
    - NVMe
    - storage
    - kubernetes
    maintainers:
    - email: kiran.mova@mayadata.io
      name: kmova
    - email: prateek.pandey@mayadata.io
      name: prateekpandey14
    - email: shovan.maity@mayadata.io
      name: shovanmaity
    name: openebs
    sources:
    - https://github.com/openebs/openebs
    urls:
    - openebs-3.8.0.tgz
    version: 3.8.0
generated: "2023-09-15T16:50:20.92390566+05:30"
